on: [push]
name: Linux_Container_Workflow

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-app:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-app:latest

    deploy:
      runs-on: ubuntu-latest
      needs: build
      
      steps:
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.CLOUDLEAGUEAPP_AZURE_CREDENTIALS }}


        - name: Deploy to containerapp
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az config set extension.use_dynamic_install=yes_without_prompt
              az containerapp registry set -n cloud-league-app -g cloudLeagueResourceGroup --server cloudleaguecr.azurecr.io --username  ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
              az containerapp update -n cloud-league-app -g cloudLeagueResourceGroup --image cloudleaguecr.azurecr.io/node-app:latest

        # - name: 'Deploy to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.RESOURCE_GROUP }}
        #     dns-name-label: cloud-league
        #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-app:latest
        #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #     environment-variables: DB_user=4dm1n157r470r DB_password=4-v3ry-53cr37-p455w0rd DB_server=app-db-server1256.database.windows.net DB_name=app-db
        #     name: cl-container-group
        #     location: 'east us'
        #     ports: 8080
            

