on: [push]
name: Linux_Container_Workflow

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
          
        #- name: 'Az CLI login'
         # uses: azure/login@v1
          #with:
           # client-id: ${{ secrets.AZURE_CLIENT_ID }}
            #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            #allow-no-subscriptions: true

        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az account show --query "{subscriptionId:id, tenantId:tenantId}"
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-app:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-app:latest

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-app:latest
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: cl-container-group
            location: 'east us'

